apiVersion: apps/v1
kind: Deployment
metadata:
  name: spam-app-deployment
spec:
  selector:
    matchLabels:
      app: spam-filter-app
  replicas: 2
  template:
    metadata:
      labels:
        app: spam-filter-app
    spec:
      containers:
      - name: spam-filter-app-container
        image: buildapp/spam-filter-app
        ports:
        - containerPort: 9090
---

apiVersion: v1
kind: Service
metadata:
  name: spam-filter-app-service
spec:
  type: NodePort
  selector:
    app: spam-filter-app
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 32000