apiVersion: apps/v1
kind: Deployment
metadata:
  name: spam-detector-deployment
spec:
  selector:
    matchLabels:
      app: spam-detector
  replicas: 3
  template:
    metadata:
      labels:
        app: spam-detector
    spec:
      containers:
      - name: spam-detector-container
        image: buildapp/spam-detector
        ports:
        - containerPort: 9090
---

apiVersion: v1
kind: Service
metadata:
  name: spam-detector-service
spec:
  type: NodePort
  selector:
    app: spam-detector
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 32000
